#!/bin/bash

read num

declare -a arrayVar=({1..num})

for i in "${arrayVar[@]}"

do

        if [ $((i%3)) -eq 0 ] && [ $((i%5)) -ne 0 ]
        then
                echo "Buzz"

        elif [ $((i%5)) -eq 0 ] && [ $((i%3)) -ne 0 ]
        then
                echo "Fizz"

        elif [ $((i%3)) -ne 0 ] && [ $((i%5)) -ne 0 ]
        then
                echo $i

        elif [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]
        then
                echo "FizzBuzz"
        fi 

done

